#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# YantraOS — Cognitive Ignition Wizard
# ═══════════════════════════════════════════════════════════════════════════════
#
# PURPOSE:
#   Centralized, interactive setup wizard that securely prompts the operator
#   for API credentials and distributes them to the correct filesystem
#   locations for both local development and ISO builds.
#
# OUTPUT TARGETS:
#   1. ./host_secrets.env                              (Local dev daemon)
#   2. ./archlive/airootfs/etc/yantra/secrets.env      (ISO overlay)
#
# SECURITY:
#   - Secret input is masked (read -s) — no terminal echo.
#   - Both output files are locked to chmod 600 immediately after write.
#   - This script itself contains NO secrets — only the generated .env files do.
#   - The .env files are gitignored; this script is not.
#
# USAGE:
#   chmod +x yantra_ignition.sh
#   ./yantra_ignition.sh
#
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── ANSI Color Tokens (Geometric Law) ─────────────────────────────────────────
BLUE='\033[36m'      # Electric Blue  #00E5FF — structural chrome
GREEN='\033[32m'     # System Green   #00FF41 — confirmations
AMBER='\033[33m'     # Terminal Amber  #FFB000 — alerts / warnings
DIM='\033[2m'        # Dimmed — sub-text
BOLD='\033[1m'       # Bold
RESET='\033[0m'      # Reset

# ── Script Root Detection ─────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Output targets
LOCAL_ENV="${SCRIPT_DIR}/host_secrets.env"
ISO_ENV_DIR="${SCRIPT_DIR}/archlive/airootfs/etc/yantra"
ISO_ENV="${ISO_ENV_DIR}/secrets.env"

# ── Functions ─────────────────────────────────────────────────────────────────

banner() {
    echo ""
    echo -e "${BLUE}${BOLD}"
    echo "  ╔═══════════════════════════════════════════════════════════════════╗"
    echo "  ║                                                                   ║"
    echo "  ║   ██╗   ██╗ █████╗ ███╗   ██╗████████╗██████╗  █████╗            ║"
    echo "  ║   ╚██╗ ██╔╝██╔══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔══██╗           ║"
    echo "  ║    ╚████╔╝ ███████║██╔██╗ ██║   ██║   ██████╔╝███████║           ║"
    echo "  ║     ╚██╔╝  ██╔══██║██║╚██╗██║   ██║   ██╔══██╗██╔══██║           ║"
    echo "  ║      ██║   ██║  ██║██║ ╚████║   ██║   ██║  ██║██║  ██║           ║"
    echo "  ║      ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝           ║"
    echo "  ║                                                                   ║"
    echo "  ║              C O G N I T I V E   I G N I T I O N                  ║"
    echo "  ║                    Secret Key Setup Wizard                         ║"
    echo "  ║                                                                   ║"
    echo "  ╚═══════════════════════════════════════════════════════════════════╝"
    echo -e "${RESET}"
    echo ""
}

info()  { echo -e "  ${BLUE}[INFO]${RESET}  $1"; }
ok()    { echo -e "  ${GREEN}[✓]${RESET}    $1"; }
warn()  { echo -e "  ${AMBER}[WARN]${RESET}  $1"; }
fail()  { echo -e "  ${AMBER}[FAIL]${RESET}  $1"; }

divider() {
    echo -e "  ${DIM}────────────────────────────────────────────────────────────${RESET}"
}

# Prompt for a secret (masked input). Args: $1=prompt_label, $2=env_var_name
# Returns the value via stdout.
prompt_secret() {
    local label="$1"
    local var_name="$2"
    local value=""

    echo ""
    echo -e "  ${BLUE}${BOLD}${label}${RESET}"
    echo -e "  ${DIM}Environment variable: ${var_name}${RESET}"
    echo -ne "  ${GREEN}▶${RESET} Enter value (input is hidden): "
    read -s value
    echo ""  # newline after masked input

    echo "${value}"
}

# Prompt for an optional secret. Args: $1=prompt_label, $2=env_var_name
prompt_optional_secret() {
    local label="$1"
    local var_name="$2"
    local value=""

    echo ""
    echo -e "  ${BLUE}${BOLD}${label}${RESET} ${DIM}(Optional — press Enter to skip)${RESET}"
    echo -e "  ${DIM}Environment variable: ${var_name}${RESET}"
    echo -ne "  ${GREEN}▶${RESET} Enter value (input is hidden): "
    read -s value
    echo ""

    echo "${value}"
}

# Write the .env file to a given path. Args: $1=filepath
write_env_file() {
    local target="$1"
    local target_dir
    target_dir="$(dirname "${target}")"

    # Ensure parent directory exists
    if [[ ! -d "${target_dir}" ]]; then
        mkdir -p "${target_dir}"
        info "Created directory: ${target_dir}"
    fi

    cat > "${target}" <<EOF
# ═══════════════════════════════════════════════════════════════════════════════
# YantraOS — Host Secrets
# Generated by yantra_ignition.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ═══════════════════════════════════════════════════════════════════════════════
# SECURITY: This file MUST be chmod 600. It is gitignored by default.
#           NEVER commit this file to version control.
# ═══════════════════════════════════════════════════════════════════════════════

# ── Google / Gemini API ───────────────────────────────────────────────────────
GEMINI_API_KEY=${KEY_GEMINI}
GOOGLE_API_KEY=${KEY_GEMINI}
GOOGLE_GENERATIVE_AI_API_KEY=${KEY_GEMINI}

# ── Pinecone (Skill Store) ───────────────────────────────────────────────────
PINECONE_API_KEY=${KEY_PINECONE}

# ── Telemetry Token (Fleet Heartbeat) ─────────────────────────────────────────
YANTRA_TELEMETRY_TOKEN=${KEY_TELEMETRY}

# ── Ollama (Local Inference — usually no key required) ────────────────────────
OLLAMA_BASE_URL=http://localhost:11434
EOF

    # Lock down permissions immediately
    chmod 600 "${target}"
}

# ── Main ──────────────────────────────────────────────────────────────────────

main() {
    banner

    info "This wizard will collect your API credentials and distribute them"
    info "to the correct filesystem locations for YantraOS operation."
    divider
    info "Target 1: ${LOCAL_ENV}"
    info "Target 2: ${ISO_ENV}"
    divider

    echo ""
    echo -e "  ${AMBER}${BOLD}⚠  All secret input is masked — nothing is echoed to the terminal.${RESET}"
    echo -e "  ${AMBER}${BOLD}⚠  Generated .env files are chmod 600 and gitignored.${RESET}"
    echo ""

    # ── Collect credentials ───────────────────────────────────────────────

    KEY_GEMINI=$(prompt_secret \
        "1/3 · Google Gemini API Key" \
        "GEMINI_API_KEY / GOOGLE_API_KEY")

    if [[ -z "${KEY_GEMINI}" ]]; then
        warn "Gemini API key was left empty. Cloud inference will be unavailable."
        warn "The daemon will attempt local-only inference via Ollama."
    else
        ok "Gemini API key captured."
    fi

    KEY_PINECONE=$(prompt_secret \
        "2/3 · Pinecone API Key" \
        "PINECONE_API_KEY")

    if [[ -z "${KEY_PINECONE}" ]]; then
        warn "Pinecone API key was left empty. Skill Store will be unavailable."
    else
        ok "Pinecone API key captured."
    fi

    KEY_TELEMETRY=$(prompt_optional_secret \
        "3/3 · Telemetry Token" \
        "YANTRA_TELEMETRY_TOKEN")

    if [[ -z "${KEY_TELEMETRY}" ]]; then
        info "Telemetry token skipped. Fleet heartbeat will be disabled."
    else
        ok "Telemetry token captured."
    fi

    # ── Distribution ──────────────────────────────────────────────────────

    divider
    echo ""
    info "Distributing credentials to target locations..."
    echo ""

    # Export for heredoc interpolation
    export KEY_GEMINI KEY_PINECONE KEY_TELEMETRY

    # Target 1: Local dev
    write_env_file "${LOCAL_ENV}"
    ok "Written: ${LOCAL_ENV}  ($(stat -c '%a' "${LOCAL_ENV}") permissions)"

    # Target 2: ISO overlay
    write_env_file "${ISO_ENV}"
    ok "Written: ${ISO_ENV}  ($(stat -c '%a' "${ISO_ENV}") permissions)"

    # ── Verification ──────────────────────────────────────────────────────

    divider
    echo ""
    echo -e "  ${GREEN}${BOLD}"
    echo "  ╔═══════════════════════════════════════════════════════════════════╗"
    echo "  ║                                                                   ║"
    echo "  ║   IGNITION COMPLETE — CREDENTIALS DISTRIBUTED                     ║"
    echo "  ║                                                                   ║"
    echo "  ║   Local Dev:   host_secrets.env .............. [LOCKED 600]        ║"
    echo "  ║   ISO Overlay: archlive/.../secrets.env ...... [LOCKED 600]        ║"
    echo "  ║                                                                   ║"
    echo "  ║   The daemon will read these via systemd EnvironmentFile          ║"
    echo "  ║   directive. No secrets touch the Git index.                      ║"
    echo "  ║                                                                   ║"
    echo "  ╚═══════════════════════════════════════════════════════════════════╝"
    echo -e "${RESET}"
    echo ""
    info "Next steps:"
    info "  1. Run the daemon:  python3 -m core.daemon"
    info "  2. Build the ISO:   cd archlive && sudo -E bash compile_iso.sh"
    echo ""
}

main "$@"
