name: Auto Assign Issues & PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign OSYantra
        uses: pozil/auto-assign-issue@2f3e41b009e91b530f973eff2538eca6b555aabb # v1
        with:
          assignees: OSYantra
          repo-token: ${{ secrets.GITHUB_TOKEN }}
